name: subtil_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.9+40

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animated_flip_counter: ^0.3.4
  app_links: ^6.3.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_typeahead: ^5.1.0
  geolocator: ^13.0.1
  google_sign_in: ^6.2.1
  http: ^1.2.0
  http_parser: ^4.0.2
  image: ^4.1.7
  image_picker: ^1.0.7
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  path: ^1.8.3
  provider: ^6.1.2
  shimmer: ^3.0.0
  timeago: ^3.2.2
  timezone: ^0.10.0
  url_launcher: ^6.3.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/coeur-fil.png
    - assets/images/coeur-fil-large.png
  fonts:
    - family: C800
      fonts:
        - asset: assets/fonts/C800-Regular.ttf
    - family: aBigDeal
      fonts:
        - asset: assets/fonts/aBigDeal.otf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_native_splash:
  branding_mode: bottom
  image: "assets/images/icon.png"
  branding: assets/images/splash-name.png
  color: "#070E20"
  android_12: 
    image: assets/images/icon.png
    icon_background_color: "#070E20"
    branding: assets/images/splash-name.png
  android: true
  ios: true
  web: false
